#define WINDOW_WIDTH_PX 800
#define WINDOW_HEIGHT_PX 600

#define PLAYER_POS_X 0.0f
#define PLAYER_POS_Y 0.0f
#define PLAYER_POS_Z -20.0f

#define PLAYER_VIEW_DIR_X 0.1f
#define PLAYER_VIEW_DIR_Y 0.1f
#define PLAYER_VIEW_DIR_Z 1.0f

#define PLAYER_REACH 5.0f